[build]
builder = "NIXPACKS"
buildCommand = "npm install --ignore-optional && npm run build --if-present"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/stats"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
